### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by timhall** [vba-blocks/vba-blocks#1]
The overall design for `vba-block.toml` and vba-blocks CLI / addin has started to firm up and it's time to focus on an MVP. The MVP should cover most of the goal workflow ~~without a central vba-blocks.com registry. The registry resolve and fetch will come in a later version and will most likely be built on the MVP foundation.~~ (this has already been done!)

(this checklist may change somewhat and will be tracked in individual issues / PRs over time)

- [x] Import components and references
- [x] Export components and references (#7)
- [x] Install registry dependency
- [x] Create from target
- [x] Create a new project (#6)
- [x] Create from an existing project
- [x] Download and install for Windows and Mac (https://github.com/vba-blocks/vba-blocks/issues/5)

**Comment by timhall** [comment]
Hit a very exciting milestone of adding a dependency with sub-dependencies to project (`json` https://github.com/vba-blocks/vba-blocks/commit/1f9ac7f87ad8a53a5944f6d040312c7695d6bbb2) and I'm refocusing this MVP to cover the high points needed for release.

**Comment by timhall** [comment]
With https://github.com/vba-blocks/vba-blocks/commit/d5364131f34810a11341a1281fd3a9503bf730fe building and importing is working on Mac!
