### ISSUE TITLE
Mac ergonomic issues in v0.2.0

### ISSUE THREAD

**Issue by timhall** [vba-blocks/vba-blocks#34]
During testing on Mac, I noticed a couple of issues that should be sorted, but weren't worth holding up the release for.

- [x] `--open` flag for `build` doesn't see to be working
- [x] Should copy files to staging for export to avoid permissions issues
- [x] Excel should open in the background / hidden, if possible
